# auto label for GitHub Discussion
name: Auto label for GitHub Discussion

on:
  discussion:
    types: [created, edited]

jobs:
  auto-label:
    name: Set label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Get ids
        id: get_ids
        env:
          CATEGORY_NAME: ${{ github.event.discussion.category.name}}
          BODY: ${{ github.event.discussion.body}}
        with:
          script: |
            const { BODY, CATEGORY_NAME } = process.env;

            if (CATEGORY_NAME !== 'Playground') return null;

            const body = BODY.toLowerCase();

            let labelId = '';
            if (body.includes('hello world')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRqXg';
            } else if (body.includes('hello')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRq3g';
            } else if (body.includes('world')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRrWA';
            }

            if (!labelId) return null;

            const discussionId = context.payload.discussion.node_id;

            console.log(`labelId: ${labelId}`);
            console.log(`discussionId: ${discussionId}`);

            return {
              labelId,
              discussionId,
            };
      - name: Add label
        if: ${{ steps.get_ids.outputs.result != null }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT: ${{ steps.get_ids.outputs.result }}
        run: |
          gh api graphql -f query='
            mutation($labelableId: ID!, $labelIds: [ID!]!) {
              addLabelsToLabelable(input: {labelableId: $labelableId, labelIds: $labelIds}) {
                labelable {
                  labels(first: 10) {
                    edges {
                      node {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f labelableId=$DISCUSSION_ID -f labelIds=$LABEL_ID
