# auto label for GitHub Discussion
name: Auto label for GitHub Discussion

on:
  discussion:
    types: [created, edited]

jobs:
  auto-label:
    name: Set label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          CATEGORY_NAME: ${{ github.event.discussion.category.name}}
          BODY: ${{ github.event.discussion.body}}
        with:
          script: |
            const { BODY, CATEGORY_NAME } = process.env;

            if (CATEGORY_NAME !== 'Playground') return;

            const body = BODY.toLowerCase();

            let labelId = '';
            if (body.includes('hello world')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRqXg';
            } else if (body.includes('hello')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRq3g';
            } else if (body.includes('world')) {
              labelId = 'LA_kwDONXJT488AAAAB0kRrWA';
            }

            if (!labelId) return;

            const discussionId = context.payload.discussion.node_id;

            console.log(`labelId: ${labelId}`);
            console.log(`discussionId: ${discussionId}`);

            const query = `mutation($discussionId: ID!, $labelIds: [ID!]!) {
              addLabelsToLabelable(input: {labelableId: $discussionId, labelIds: $labelIds}) {
                clientMutationId
              }
            }`;
            const variables = {
              discussionId,
              labelIds: [labelId],
            };

            const result = await github.graphql({ query, variables });
            console.log(result);
