# auto label for GitHub Discussion
name: Auto label for GitHub Discussion

on:
  discussion:
    types: [created, edited]

jobs:
  auto-label:
    name: Set label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          CATEGORY_NAME: ${{ github.event.discussion.category.name}}
          BODY: ${{ github.event.discussion.body}}
        with:
          script: |
            const { BODY, CATEGORY_NAME } = process.env;

            if (CATEGORY_NAME !== 'Playground') return;

            const body = BODY.toLowerCase();

            let label = '';
            if (body.includes('hello world')) {
              label = 'Hello World';
            } else if (body.includes('hello')) {
              label = 'Hello Only';
            } else if (body.includes('world')) {
              label = 'World Only';
            }

            if (!label) return

            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.discussion.number,
              labels: [label]
            });
